### ISSUE TITLE
Error when adding/removing multiple rows

### ISSUE THREAD

**Issue by dansmith01** [jrowen/rhandsontable#126]
Here is some code to reproduce the issue I'm seeing:

```
library(shiny)
library(rhandsontable)

ui <- fluidPage(
  rHandsontableOutput("in.table"),
  actionButton("Save", "Save")
)

server <- function(input, output) {
  
  output$in.table <- renderRHandsontable({
    rhandsontable(data.frame("UserID" = 1:5, "Name" = LETTERS[1:5]))
  })
  
  observeEvent(input$Save, {
    df <- hot_to_r(input$in.table)
    print(df)
  })
  
}

shinyApp(ui = ui, server = server)
```

Insert/delete as follows to cause the error.
1. Click on "B" row and add a row above.
2. Click on "B" row again and add another row above.
3. Delete "D" row.
4. Click "Save".

R crashes with the following message:

```
Warning: Error in row.names<-.data.frame: invalid 'row.names' length
Stack trace (innermost first):
    71: row.names<-.data.frame
    70: row.names<-
    69: rownames<-
    68: <Anonymous>
    67: do.call
    66: hot_to_r
    65: observeEventHandler [C:\Users\...\app.R#20]
     1: shiny::runApp
```

I'm using the latest version of rhandsontable installed today with `devtools::install_github("jrowen/rhandsontable")`.

**Comment by bklingen** [comment]
This is the same error message I get when just pasting in a column longer than the current table, so seems related. Issue #124

**Comment by dansmith01** [comment]
In a non reactive environment, e.g. running on the R console:
`rhandsontable::rhandsontable(data.frame("UserID" = 1:5, "Name" = LETTERS[1:5]))`
Allow you to insert rows, but does not immediately react to deleting rows. As far as I know, there is no way to invoke `hot_to_r` and see if the error is the same.

Are you able to reproduce the error using the code I provided?

**Comment by jrowen** [comment]
I just pushed an update that will hopefully fix these issues.  Please let me know.  Thanks.

**Comment by dansmith01** [comment]
Hi @jrowen, yep, that fixed it, thanks!!

**Comment by jrowen** [comment]
Great.  Thanks.

**Comment by maryskalicky** [comment]
I'm having the same problem.  If I delete one row - no problem.  But if I delete another row then I get the same error.

I just installed the dev version (devtools::install_github("jrowen/rhandsontable")) but it is still happening.

Is this a different issue?

**Comment by Frank72** [comment]
I also have the same problem: can delete one row, but not few.
Is there an update on this issue please?
